export PATH="$PATH:$HOME/go/bin:$HOME/fvm/default/bin"
. "$HOME/.cargo/env"
source ~/.bash_completion/alacritty

export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"

eval "$(starship init bash)"
