#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# four virtual desktop named I II III IV
bspc monitor -d I II III IV V VI VII
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle    true
# bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# border
bspc config focused_border_color "#e28743" 
bspc config normal_border_color  "#2f343f"
bspc config active_border_color  "#2f343f"
bspc config presel_feedback_color "#e28743"

# ============================================================
# Mice bindings ( pointer_modeifier + mouse actoin)
bspc config pointer_modifier mod4 # win key
bspc config pointer_action1 move # left
bspc config pointer_action2 resize_side # center (press)
bspc config pointer_action3 resize_corner # right

# ============================================================
# rules
# use 'xprop | grep WM_CLASS' to see program class
# (<class_name>|*)[:(<instance_name>|*)[:(<name>|*)]], when the wm_name is changable(like emacs, firefox is opposite),
#   the rule will be useless. In this case, please consider use external_rules
bspc rule -a floating state=floating sticky=on rectangle=1600x1000+800+500
bspc rule -a ranger sticky=on state=floating rectangle=1433x928+1739+67

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Logseq state=tiled

bspc rule -a fullscreen state=fullscreen
bspc rule -a thunderbird state=fullscreen
bspc rule -a yesplaymusic state=fullscreen
bspc rule -a discord state=fullscreen
bspc rule -a TelegramDesktop state=fullscreen
bspc rule -a electronic-wechat state=fullscreen
bspc rule -a MEGAsync state=floating rectangle=600x600+2200+100
bspc rule -a Pqiv border=off state=floating


bspc config external_rules_command /home/zarkli/.config/bspwm/external_rules.sh


# ============================================================
# configuration
xsetroot -cursor_name left_ptr &

# ============================================================
# auto start
feh --bg-center $HOME/Pictures/background/1.jpg
picom &
$HOME/.config/polybar/launch.sh
dunst &
nm-applet &
udiskie &
fcitx5 -d &
/home/zarkli/Public/Clash_for_Windows/cfw & 
# kdeconnect-indicator &
xautolock -time 15 -locker 'betterlockscreen -l dimblur' &
blueman-applet &

redshift &
megasync &
$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox --minimize &
/usr/bin/telegram-desktop -workdir /home/zarkli/.local/share/TelegramDesktop/ -autostart &
greenclip daemon &
emacs --daemon &
jgmenu --hide-on-startup &
