#!/bin/bash
#sync all config files

#link to other variables of folder
folder_vars=("config_folders")
# folders in the ~/.config directory
config_folders=("alacritty" "bspwm" "dunst" "fish" "neofetch" 
  "picom" "polybar", "ranger", "redshift" "rofi", "sxhkd")

for var in ${folder_vars[@]}; do 
  folders=$var[@]
  for f2 in ${folders}; do
    echo $f2
  done
done

