config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_fish:
    src: config/fish
    dst: ~/.config/fish
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_redshift:
    src: config/redshift
    dst: ~/.config/redshift
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_eww:
    src: config/eww
    dst: ~/.config/eww
  d_jgmenu:
    src: config/jgmenu
    dst: ~/.config/jgmenu
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_mybin:
    src: myBin
    dst: ~/myBin
  f_xsession:
    src: xsession
    dst: ~/.xsession
    chmod: '755'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_rofimoji.rc:
    src: config/rofimoji.rc
    dst: ~/.config/rofimoji.rc
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
    chmod: '644'
  f_settings.json:
    src: config/Code - OSS/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  d_share_rofi:
    src: local/share/rofi
    dst: ~/.local/share/rofi
  d_share_ranger:
    src: local/share/ranger
    dst: ~/.local/share/ranger
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_blender:
    src: config/blender
    dst: ~/.config/blender
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
    chmod: '600'
  f_yarnrc:
    src: yarnrc
    dst: ~/.yarnrc
  f_config.toml:
    src: cargo/config.toml
    dst: ~/.cargo/config.toml
  d_matter:
    src: Public/matter
    dst: ~/Public/matter
  f_ranger.desktop:
    src: local/share/applications/ranger.desktop
    dst: ~/.local/share/applications/ranger.desktop
  f_discord.desktop:
    src: local/share/applications/discord.desktop
    dst: ~/.local/share/applications/discord.desktop
  d_uair:
    src: config/uair
    dst: ~/.config/uair
  d_usr:
    src: local/share/wudao-dict/usr
    dst: ~/.local/share/wudao-dict/usr
  f_nyanlooped.mp3:
    src: Music/nyanlooped.mp3
    dst: ~/Music/nyanlooped.mp3
  d_rofimoji:
    src: local/share/rofimoji
    dst: ~/.local/share/rofimoji
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_zoxide:
    src: local/share/zoxide
    dst: ~/.local/share/zoxide
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_gammastep:
    src: config/gammastep
    dst: ~/.config/gammastep
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
    chmod: '700'
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  d_swappy:
    src: config/swappy
    dst: ~/.config/swappy
  d_paru:
    src: config/paru
    dst: ~/.config/paru
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_theme:
    src: local/share/delta/theme
    dst: ~/.local/share/delta/theme
  d_notes:
    src: notes
    dst: ~/notes
  f_user.js:
    src: mozilla/firefox/user.js
    dst: ~/.mozilla/firefox/user.js
  f_gitmessage.txt:
    src: gitmessage.txt
    dst: ~/.gitmessage.txt
  f_env:
    src: config/go/env
    dst: ~/.config/go/env
  d_cargo:
    src: config/cargo
    dst: ~/.config/cargo
  d_fcitx5:
    src: config/fcitx5
    dst: ~/.config/fcitx5
    chmod: '700'
  d_go:
    src: config/go
    dst: ~/.config/go
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_profile:
    src: profile
    dst: ~/.profile
  f_gdbinit:
    src: gdbinit
    dst: ~/.gdbinit
  d_helix:
    src: config/helix
    dst: ~/.config/helix
  f_code-flags.conf:
    src: config/code-flags.conf
    dst: ~/.config/code-flags.conf
  d_texmf:
    src: texmf
    dst: ~/texmf
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_config:
    src: config/sway/config
    dst: ~/.config/sway/config
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_gitui:
    src: config/gitui
    dst: ~/.config/gitui
profiles:
  myArch:
    dotfiles:
    - d_alacritty
    - d_bspwm
    - d_dunst
    - d_fish
    - d_neofetch
    - d_picom
    - d_polybar
    - d_ranger
    - d_redshift
    - d_rofi
    - d_sxhkd
    - d_eww
    - d_jgmenu
    - d_zathura
    - d_mybin
    - f_xsession
    - f_xresources
    - f_ideavimrc
    - f_vimrc
    - f_rofimoji.rc
    - f_mimeapps.list
    - f_settings.json
    - d_share_rofi
    - d_share_ranger
    - f_gitconfig
    - d_blender
    - f_npmrc
    - f_yarnrc
    - f_config.toml
    - d_matter
    - f_ranger.desktop
    - f_discord.desktop
    - d_uair
    - d_usr
    - f_nyanlooped.mp3
    - d_rofimoji
    - d_hypr
    - d_zoxide
    - d_wofi
    - d_waybar
    - d_gammastep
    - d_gtk-3.0
    - d_gtk-4.0
    - f_gtkrc-2.0
    - d_swappy
    - d_paru
    - d_kitty
    - d_theme
    - d_notes
    - f_user.js
    - f_gitmessage.txt
    - f_env
    - d_cargo
    - d_fcitx5
    - d_go
    - f_bashrc
    - f_profile
    - f_gdbinit
    - d_helix
    - f_code-flags.conf
    - d_texmf
    - f_starship.toml
    - f_gitignore_global
    - f_config
    - d_sway
    - d_swaylock
    - d_bat
    - d_gitui
