# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml

[opener]
# modify built-in
play = [
	{ exec = 'mpv --force-window "$@"', block = true, for = "unix" },
	{ exec = 'mpv "%1"', orphan = true, for = "windows" },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

# my-own
text = [
  { exec = 'env EMACS-MIN=1 nemacs --eval "(mk/global-read-only-mode)" "$@"', block=true, desc = "emacs viewer"},
  { exec = 'bat --paging=always -p --pager="less -Ri" "$@"', block=true, desc = "bat"},
  { exec = 'less -i "$@" ', block=true, desc = "cat"},
]
image = [
  { exec = 'inkview "$@"', desc = "inkview"},
]
mk_common = [
  { exec = 'dragon-drop "$@"', desc= "dragon-drop"}
]
db = [
  { exec = 'litecli "$@"', desc = "litecli", block = true}
]
font = [
  # font preview: https://github.com/sdushantha/fontpreview
  { exec = 'fontpreview "$@"', desc = "preview" }
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal", "mk_common"] },
  { name = "*.sqlite", use = ["db", "reveal", "mk_common"]},
  

	{ mime = "text/*",  use = [ "text", "edit", "reveal", "mk_common"  ] },
	{ mime = "image/*", use = [ "open", "image", "reveal", "mk_common"] },
	{ mime = "video/*", use = [ "play", "reveal", "mk_common" ] },
	{ mime = "audio/*", use = [ "play", "reveal", "mk_common" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal", "mk_common" ] },

	{ mime = "application/json", use = [ "edit", "reveal", "mk_common" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal", "mk_common" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal", "mk_common" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal", "mk_common" ] },
  
	{ name = "*.ttf",  use = [ "font", "open", "reveal", "mk_common"  ] },
	{ name = "*.otf",  use = [ "font", "open", "reveal", "mk_common"  ] },
	{ name = "*.woff",  use = [ "font", "open", "reveal", "mk_common"  ] },
	{ name = "*.woff2",  use = [ "font", "open", "reveal", "mk_common"  ] },

	{ mime = "*", use = [ "open", "reveal", "mk_common" ] },
]
