theme = "solarized_light"

[editor]
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker] 
hidden = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[keys.normal]
A-x = "command_palette"
X = "extend_line_above"
g = { c = "toggle_comments" }

[keys.insert]
A-x = "command_palette"
j = { k = "normal_mode" }
C-h = "move_char_left"
C-l = "move_char_right"
C-j = "move_line_down"
C-k = "move_line_up"
