#!/usr/bin/env bash
# --------------------
# @Origin: https://wiki.archlinux.org/title/Dunst#Using_dunstify_as_volume/brightness_level_indicator
# @Modifier: Zarkli Leonardo(mr.ziqiyang@gmail.com)
# @Time: Wed Dec 14 22:21:19 2022;
# --------------------
# brightness_notify

# Arbitrary but unique message tag
msgTag="mybrightnessinfo"

# Query amixer for the current volume and whether or not the speaker is muted
brightness="$(brightnessctl | sed -n '2p' | sed 's/.*(\([0-9]*\)%).*/\1/')"

dunstify -a "BrightnessInfo" -u low -i keyboard-brightness-symbolic -h string:x-dunst-stack-tag:$msgTag \
-h int:value:"$brightness" "Brightness: ${brightness}%" -t 1000

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
