#!/usr/bin/env sh
set -e

xclip -selection clipboard -t image/png -o > /tmp/clipboard.png

rect="$(slop -b 5 -l -c 0.3,0.4,0.6,0.4)" && {
    bspc rule -a '*' -o state=floating rectangle="$rect"
    feh -ZF /tmp/clipboard.png &
}
