#!/usr/bin/env bash
# --------------------
# @Origin: https://wiki.archlinux.org/title/Dunst#Using_dunstify_as_volume/brightness_level_indicator
# @Modifier: Zarkli Leonardo(mr.ziqiyang@gmail.com)
# @Time: Wed Dec 14 22:21:19 2022;
# --------------------
# volume_notify

# Arbitrary but unique message tag
msgTag="myvolume"

# Change the volume using alsa(might differ if you use pulseaudio)
amixer -c 0 set master "$@" > /dev/null

# Query amixer for the current volume and whether or not the speaker is muted
volume="$(amixer get Master | tail -1 | sed -e 's/.*\[\(.*\)%\] \[\(.*\)\]/\1/g')"
mute="$(amixer get Master | tail -1 | sed -e 's/.*\[\(.*\)%\] \[\(.*\)\]/\2/g')"
if [[ $volume == 0 || "$mute" == "off" ]]; then
    # Show the sound muted notification
    dunstify -a "VolumeInfo" -u low -i audio-volume-muted-symbolic -h string:x-dunst-stack-tag:$msgTag \
        "volume muted" -t 1000
else
    # Show the volume notification
    dunstify -a "VolumeInfo" -u low -i audio-headphones -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "Volume: ${volume}%" -t 1000
fi

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
