#!/bin/bash
# use rofi to open zathura history file
# origin: https://gist.github.com/kidpixo/6faaf4404260be21040951cdfca97dcb 
# modified by Zarkli Leonardo

# read 500 lines in the end
# save filepaths in history to array, reverse  order
readarray -t Data < <(tail -500 ~/.local/share/zathura/history | grep -o '/.*\.[[:alpha:]]\{,3\}' | tac)

# loop and unset not existing files 
for i in "${!Data[@]}"
do  
    if ! [ -e "${Data[$i]}" ]; then
        # echo "${Data[$i]} does not exist."
        unset 'Data[$i]'
    else 
        Data[$i]=${Data[$i]/$HOME/\~}
        # echo "${Data[$i]} exists."
    fi
done
selected=$( ( IFS=$'\n'; echo "${Data[*]}" ) | rofi -dmenu -i -markup-rows --display-name ">>>")
selected=${selected/\~/$HOME}

# exit if nothing is selected
[[ -z $selected ]] && exit

# prevent opening not existing file 
if [ -f "$selected" ]; then
    zathura "$selected"
else 
    exit
fi

exit 0
