[alias]     # 命令别名
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"

[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
