import:
  - ~/.config/alacritty/colorschemes/catppuccin-frappe.yml

window:
  decorations: none
  opacity: 0.8
  startup_mode: Maximized
  title: Leonardo Zarkli's Alacritty
  dynamic_title: true
  decorations_theme_variant: 'dark'
font:
  normal:
    family: 'FiraCode Nerd Font'
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 12.0
draw_bold_text_with_bright_colors: true

live_config_reload: true

shell:
 program: /usr/bin/fish
 args:
   - --login

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
