#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# four virtual desktop named I II III IV
bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# use 'xprop | grep WM_CLASS' to see program class
bspc rule -a floating state=floating sticky=on rectangle=1600x1000+800+500

feh --bg-center $HOME/Pictures/background/1.jpg
picom &
$HOME/.config/polybar/launch.sh
dunst &
$HOME/.config/bspwm/autostart.sh
udiskie &
