loop_on_end=true

[defaults]
# note: there shouldn't be any space in the variables
format = "{name} {time}\n"

[[sessions]]
name = "work"
duration = "30m"
# command = "notify-send 'Work Done!'; paplay /usr/share/sounds/freedesktop/stereo/complete.oga"
command = "notify-send 'Work Done!'; mpg123 -f -19660 /home/zarkli/Music/nyanlooped.mp3"

[[sessions]]
name = "rest"
duration = "3m"
command = "notify-send 'Rest Done!'; mpg123 -f -19660 /home/zarkli/Music/nyanlooped.mp3; /home/zarkli/myBin/phone_notify 继续学习啦！> /dev/null 2>&1"
