loop_on_end=true

[defaults]
# note: there shouldn't be any space in the variables
format = "{name} {time}\n"

[[sessions]]
name = "work"
duration = "30m"
# command = "notify-send 'Work Done!'; paplay /usr/share/sounds/freedesktop/stereo/complete.oga"
command = "/home/zarkli/.config/uair/work"

[[sessions]]
name = "rest"
duration = "5m"
command = "/home/zarkli/.config/uair/reset"
